sonar.projectKey=mac-control-mcp
sonar.projectName=mac-control-mcp
sonar.host.url=http://127.0.0.1:9001

sonar.language=py
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPath=coverage.xml
sonar.coverage.exclusions=tests/**
sonar.cpd.exclusions=**/*.json, tests/**
sonar.sourceEncoding=UTF-8
sonar.python.version=3.12
